#!/usr/bin/perl
use strict;
use warnings;

use POE;
use Helpr::Bot;

Helpr::Bot->new({
  ($ENV{HELPR_USERNAME} ? (username => $ENV{HELPR_USERNAME}) : ()),
  ($ENV{HELPR_PASSWORD} ? (password => $ENV{HELPR_PASSWORD}) : ()),
});

$poe_kernel->run;
